require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.7.2
  DisabledByDefault: true
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - '**/tmp/**/*'
    - '**/templates/**/*'
    - '**vendor/**/*'
    - '**/node_modules/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'test/**/*'

Performance:
  Exclude:
    - '**/test/**/*'

Rails:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false
  Exclude:
    - 'db/migrate/*'
    - 'config/application.rb'

Rails/ReversibleMigration:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/StringLiterals:
  Enabled: false
  EnforcedStyle: double_quotes

Style/WordArray:
  MinSize: 3

Metrics/AbcSize:
  Max: 100

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 20

Metrics/BlockNesting:
  Max: 5

Layout/LineLength:
  Max: 160

Metrics/MethodLength:
  Max: 100

Metrics/ClassLength:
  Max: 500

Metrics/ModuleLength:
  Max: 500

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Naming/PredicateName:
  ForbiddenPrefixes:
    - "is_"
    - "have_"
  NamePrefix:
    - "is_"
    - "have_"

Layout/SpaceBeforeFirstArg:
  Exclude:
    - 'db/migrate/*.rb'

Layout/MultilineOperationIndentation:
  Enabled: false
